---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths: 
  "/api/post":
    get:
      summary: list posts
      security:
      - bearer_auth: []
      responses:
        '200':
          description: successful
        '401':
          description: authentication failed
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
# 1) Define the security scheme type (HTTP bearer)
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
# 2) Apply the security globally to all operations
security:
  - bearerAuth: []         # use the same name as above
